### Introduction to NumPy
1. NumPy **(Numerical Python)** is a fundamental library for numerical computing in Python. It provides support for arrays, matrices, and high-level mathematical functions.
2. It includes a comprehensive collection of packages containing mathematical functions for performing statistical analysis, linear algebra operations, and so on.
3. **Broadcasting**:
      - It is one of NumPy's key feature which allows operation on arrays (matrices) of different shapes in a way that avoids unnecessary data duplication.

In [53]:
import numpy as np

### 1) Array Creation

In [54]:
# Create a 1d array of integers from 1 to 10
arr1 = np.array([i for i in range(1, 11)])

arr1, f"Dimension: {arr1.ndim}"

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), 'Dimension: 1')

In [58]:
# Create a 2d array with random float values of shape (3, 4) = (rows, cols)
arr2 = np.random.rand(3, 4)

arr2, f"Dimension: {arr2.ndim}"

(array([[0.84594348, 0.3779838 , 0.89060579, 0.63957671],
        [0.69291441, 0.34265492, 0.70033623, 0.0408215 ],
        [0.56405681, 0.21479088, 0.65299604, 0.11930519]]),
 'Dimension: 2')

In [59]:
# Create a 3d array of zeroes with shape (2, 3, 4) = (blocks, rows, cols)
arr3 = np.zeros((2, 3, 4)) # In this case, two blocks (or layers), each containing a 3x4 matrix
arr3, f"Dimension: {arr3.ndim}"

(array([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],
 
        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]),
 'Dimension: 3')

In [60]:
# Create an array of shape(4,3) with all the elements '7' and dtype 'int'
arr4 = np.ones((4, 3), dtype=int) * 7
arr4

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

### np.arange
- Syntax:
  - `arange(stop)`: Generates values from 0 to `stop` (exclusive) -> [0, stop)
  - `arange(start, stop)`: Generates values from `start` to `stop` (exclusive) -> [start, stop).
  - `arange(start, stop, step)`: Generates values from `start` to `stop` (exclusive) with a `step` interval  -> [start, stop)

In [61]:
# Usage
a = np.arange(10)
b = np.arange(10, 20)
c = np.arange(10, 30, 3)
a, b, c

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
 array([10, 13, 16, 19, 22, 25, 28]))

### like
- It is used to create new arrays with the same shape and type as a given array.
- `numpy.ones_like(a, dtype=None, order='K', subok=True, shape=None)`: filled with ones
- `numpy.empty_like(a, dtype=None, order='K', subok=True, shape=None)`: filled with uninitialized values

In [62]:
# Usage
np.ones_like(arr2), np.empty_like(arr2)

(array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 array([[0.84594348, 0.3779838 , 0.89060579, 0.63957671],
        [0.69291441, 0.34265492, 0.70033623, 0.0408215 ],
        [0.56405681, 0.21479088, 0.65299604, 0.11930519]]))

### NumPy Array Slicing

Slicing in NumPy arrays allows you to access a subset of an array. This is useful for manipulating and analyzing specific sections of data without copying the array. Slicing works with multi-dimensional arrays and follows the pattern of `start:stop:step`.

**Note**: One main distinction between python list and numpy array is that the slice is not the copy of original list, rather it's the original list itself.

In [67]:
# 1d array
arr1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr1[2:7], arr1[1:9:2] # with step

(array([2, 3, 4, 5, 6]), array([1, 3, 5, 7]))

In [69]:
# 2d array
arr2 = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr2[1:3, 0:2], arr2[::2, ::2] # with step

(array([[3, 4],
        [6, 7]]),
 array([[0, 2],
        [6, 8]]))

In [72]:
# Negative indices
arr1[:5], arr1[::-1] # reverse

(array([0, 1, 2, 3, 4]), array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]))

In [74]:
# Accessing rows and cols
arr2[:, 1], arr2[1, :]

(array([1, 4, 7]), array([3, 4, 5]))

In [82]:
# Boolean Indexing
lang = np.array(["JAVA", "PYTHON", "RUST", "GO"])
arr1[arr1 > 5], lang == "PYTHON"

(array([6, 7, 8, 9]), array([False,  True, False, False]))

In [80]:
# Assigning same values to a range
slice = np.arange(20)
slice[10:16] = 20
slice

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 20, 20, 20, 20, 20, 20, 16,
       17, 18, 19])

In [81]:
# We can avoid changes to the original list by
copied_slice = slice.copy()
copied_slice

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 20, 20, 20, 20, 20, 20, 16,
       17, 18, 19])

#### Masking and Indexing

In [3]:
import numpy as np
mask_arr = np.linspace(2, 50, 20, dtype=int).reshape(4, -1)
mask_arr

array([[ 2,  4,  7,  9, 12],
       [14, 17, 19, 22, 24],
       [27, 29, 32, 34, 37],
       [39, 42, 44, 47, 50]])

In [114]:
# Creating the mask (applicable in one-hot encoding)
mask = mask_arr % 2 == 1
mask

array([[False, False,  True,  True, False],
       [False,  True,  True, False, False],
       [ True,  True, False, False,  True],
       [ True, False, False,  True, False]])

In [116]:
# Getting only the masked values
masked_arr = mask_arr[mask]
masked_arr

array([ 7,  9, 17, 19, 27, 29, 37, 39, 47])

In [109]:
# Creating a BINGO card
arr = np.arange(1, 26)
np.random.shuffle(arr)

bingo = arr.reshape(5, -1) # (rows, cols)
bingo

array([[17, 25, 14,  8,  7],
       [22, 19,  6, 15, 12],
       [11, 18, 10, 21,  9],
       [16, 20, 13,  2,  1],
       [ 3, 23,  5,  4, 24]])

#### Mathematics

In [119]:
# Arithmetic operations
x = np.array([4, 19, 23, 90])
y = np.array([2, 13, 22, 32])

# Two methods for element-wise addition
x + y, np.add(x, y)

(array([  6,  32,  45, 122]), array([  6,  32,  45, 122]))

*Note: Subtraction, Multiplication and Division can be carried out in the same fashion using `np.subtract`, `np.multiply` and `np.divide`.  
For Floor division `np.floor_division` can be used.*

In [125]:
# Trigonometric operations
x = np.array([0., 1., 30, 90, 120, 150, 180])

print("sine:", np.sin(x))
print("cosine:", np.cos(x))
print("tangent:", np.tan(x))

sine: [ 0.          0.84147098 -0.98803162  0.89399666  0.58061118 -0.71487643
 -0.80115264]
cosine: [ 1.          0.54030231  0.15425145 -0.44807362  0.81418097  0.69925081
 -0.59846007]
tangent: [ 0.          1.55740772 -6.4053312  -1.99520041  0.71312301 -1.02234624
  1.33869021]


Calculation of inverse sine, inverse cosine, and inverse tangent, element-wise.

In [126]:
x = np.array([-1, 0, 1])

print("sine:", np.arcsin(x))
print("cosine:", np.arccos(x))
print("tangent:", np.arctan(x))

sine: [-1.57079633  0.          1.57079633]
cosine: [3.14159265 1.57079633 0.        ]
tangent: [-0.78539816  0.          0.78539816]


Convert angles from radians to degrees.

In [127]:
x = np.array([-np.pi, -np.pi/2, np.pi/2, np.pi])

output_1 = np.degrees(x)
output_2 = np.rad2deg(x)
assert np.array_equiv(output_1, output_2)
print(f'out1: {output_1} and out2: {output_2}')

out1: [-180.  -90.   90.  180.] and out2: [-180.  -90.   90.  180.]


Convert angles from degrees to radians.

In [128]:
x = np.array([-180.,  -90.,   90.,  180.])

output_1 = np.radians(x)
output_2 = np.deg2rad(x)
assert np.array_equiv(output_1, output_2)
print(f'out1: {output_1} and out2: {output_2}')

out1: [-3.14159265 -1.57079633  1.57079633  3.14159265] and out2: [-3.14159265 -1.57079633  1.57079633  3.14159265]


#### Statistics and Linear Algebra

In [129]:
x = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [130]:
x.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [131]:
sum_a = x.sum()
sum_a

36

In [132]:
sum_across_col = x.sum(axis=0)
sum_across_col

array([ 6,  8, 10, 12])

In [133]:
sum_across_row = x.sum(axis=1)
sum_across_row

array([10, 26])

In [134]:
mean_a = x.mean()
mean_a

4.5

In [135]:
mean_across_col = x.mean(axis=0)
mean_across_col

array([3., 4., 5., 6.])

In [136]:
mean_across_row = x.mean(axis=1)
mean_across_row

array([2.5, 6.5])

In [137]:
array_a = np.array([[1, 2, 3, 4, 5],[1, 3, 4, 6, 7]])
array_b = np.array([[2, 4, 6, 8, 10], [1, 3, 5, 7, 9]])

In [138]:
array_a * 3

array([[ 3,  6,  9, 12, 15],
       [ 3,  9, 12, 18, 21]])

### Dot Product

The dot product, also known as the scalar product or inner product, is a binary operation that takes two equal-length sequences of numbers (vectors) and returns a single number. In the context of linear algebra, the dot product of two vectors $ \overrightarrow{a} $ and $ \overrightarrow{b} $ is defined as:

$$
\overrightarrow{a} \cdot \overrightarrow{b} = \sum_{i=1}^{n} a_i b_i
$$

Where:
- $ \overrightarrow{a} = [a_1, a_2, ..., a_n] $ and $ \overrightarrow{b} = [b_1, b_2, ..., b_n] $ are the vectors.
- $ n $ is the number of elements in each vector.
- $ \overrightarrow{a} \cdot \overrightarrow{b} = a_1 \cdot b_1 + a_2 \cdot b_2 + a_3 \cdot b_3 + ... + a_n \cdot b_n $

In [145]:
# Example
dot_product = array_a.dot(array_b.T)
dot_product

array([[110,  95],
       [156, 135]])

#### Datetime Module

In [147]:
from datetime import datetime

In [148]:
def calculate_sum_from_numpy(n):
    a = np.arange(n) ** 2
    b = np.arange(n) ** 3
    c = a + b
    return c

In [149]:
def calculate_sum_from_list_loops(n):
    a = list(range(n))
    b = list(range(n))
    c = []
    for i in range(len(a)):
        a[i] = i ** 2
        b[i] = i ** 3
        c.append(a[i] + b[i])
    return c

In [150]:
start = datetime.now()
c = calculate_sum_from_list_loops(100000)
delta = datetime.now() - start
print("The last 2 elements of the sum", c[-2:])
print("Python Loop and List elapsed time in microseconds", delta)

The last 2 elements of the sum [999950000799996, 999980000100000]
Python Loop and List elapsed time in microseconds 0:00:00.052933


In [152]:
start_numpy = datetime.now()
c = calculate_sum_from_numpy(100000)
delta_numpy = datetime.now() - start_numpy
print("The last 2 elements of the sum", c[-2:])
print("Numpy elapsed time in microseconds", delta_numpy)

The last 2 elements of the sum [999950000799996 999980000100000]
Numpy elapsed time in microseconds 0:00:00.001522
