### 1) Array Creation

In [2]:
import numpy as np

In [47]:
# Create a 1d array of integers from 1 to 10
arr1 = np.arange(1, 11)

arr1, f"Dimension: {arr1.ndim}"

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), 'Dimension: 1')

In [4]:
# Create a 2d array with random float values of shape (3, 4) = (rows, cols)
arr2 = np.random.rand(3, 4)

arr2, f"Dimension: {arr2.ndim}"

(array([[0.55346363, 0.82714183, 0.56815566, 0.33814986],
        [0.2558847 , 0.79485646, 0.05596673, 0.10007398],
        [0.31999841, 0.74232809, 0.84324837, 0.20634267]]),
 'Dimension: 2')

In [6]:
# Create a 3d array of zeroes with shape (2, 3, 4) = (blocks, rows, cols)
arr3 = np.zeros((2, 3, 4)) # In this case, two blocks (or layers), each containing a 3x4 matrix

arr3, f"Dimension: {arr3.ndim}"

(array([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],
 
        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]),
 'Dimension: 3')

### 2) Array Operations

In [14]:
# Define the arrays
arr_a = np.array([2, 4, 6, 8])
arr_b = np.array([1, 3, 5, 7])

In [26]:
# Addition
arr_a + arr_b, np.add(arr_a, arr_b)

(array([ 3,  7, 11, 15]), array([ 3,  7, 11, 15]))

In [28]:
# Subtraction
arr_a - arr_b, np.subtract(arr_a, arr_b)

(array([1, 1, 1, 1]), array([1, 1, 1, 1]))

In [29]:
# Multiplication
arr_a * arr_b, np.multiply(arr_a, arr_b)

(array([ 2, 12, 30, 56]), array([ 2, 12, 30, 56]))

In [30]:
# Division
arr_a / arr_b, np.divide(arr_a, arr_b)

(array([2.        , 1.33333333, 1.2       , 1.14285714]),
 array([2.        , 1.33333333, 1.2       , 1.14285714]))

In [21]:
# Mean
np.mean(arr_a)

5.0

In [23]:
# Median
np.median(arr_b)

4.0

In [25]:
# Standard Deviation
np.std(arr_a)

2.23606797749979

In [38]:
arr_x = np.array([i for i in range(1, 13)])
np.random.shuffle(arr_x)

In [42]:
# Reshape the array into a 2d array of shape (3, 4)
assert np.array_equal(arr_x.reshape(3, -1), arr_x.reshape(3, 4))
arr_x.reshape(3, -1), arr_x.reshape(3, 4)

(array([[11,  5, 10,  8],
        [ 6,  7,  3,  9],
        [12,  1,  2,  4]]),
 array([[11,  5, 10,  8],
        [ 6,  7,  3,  9],
        [12,  1,  2,  4]]))

### 3) Array Indexing and Slicing

In [54]:
# Define a 2d array
arr_1 = np.random.randint(2, 20, size=(3, 4))
arr_1

array([[ 2,  8,  2,  2],
       [ 6,  5, 14,  2],
       [16, 17,  2, 16]])

In [57]:
# First row
arr_1[:1, :]

array([[2, 8, 2, 2]])

In [58]:
# Last Column
arr_1[:, -1]

array([ 2,  2, 16])

In [63]:
# Reversed array
arr_a[::-1]

array([8, 6, 4, 2])

In [67]:
# Boolean Indexing
condition = arr_1 > 7
arr_1[condition]

array([ 8, 14, 16, 17, 16])

### 4) Array Broadcasting

In [71]:
# Create a 1D array
arr1d = np.array([1, 2, 3])

In [72]:
# Create a 2D array
arr2d = np.array([[4, 5, 6],
                  [7, 8, 9]])

In [73]:
# Adding a scalar value to a 2d array
arr2d + 7

array([[11, 12, 13],
       [14, 15, 16]])

In [79]:
# Multiply the arrays
arr1d * arr2d

array([[ 4, 10, 18],
       [ 7, 16, 27]])

### 5) Linear Algebra

In [85]:
# 1d Arrays
arr_a, arr_b

(array([2, 4, 6, 8]), array([1, 3, 5, 7]))

In [86]:
arr_a.dot(arr_b), np.dot(arr_a, arr_b)

(100, 100)

In [99]:
# 2d Arrays
arr_2x = arr_x.reshape(3, -1).T
arr_1, arr_2x

(array([[ 2,  8,  2,  2],
        [ 6,  5, 14,  2],
        [16, 17,  2, 16]]),
 array([[11,  6, 12],
        [ 5,  7,  1],
        [10,  3,  2],
        [ 8,  9,  4]]))

In [100]:
# Matrix multiplication
np.matmul(arr_1, arr_2x)

array([[ 98,  92,  44],
       [247, 131, 113],
       [409, 365, 277]])

In [104]:
# Create a square matrix
A = np.array([[7, 9],
              [6, 4]])

In [105]:
# Inverse of A
inv_A = np.linalg.inv(A)
inv_A

array([[-0.15384615,  0.34615385],
       [ 0.23076923, -0.26923077]])

In [106]:
# Determinant of A
det_A = np.linalg.det(A)
det_A

-25.99999999999999